name: "Setup"

description: "Setup Rust tools"

runs:
  using: "composite"
  steps:
    - run: rustup toolchain install --profile minimal --component clippy --component rustfmt 1.86.0
      shell: bash

    - name: Restore CI tools
      id: cache-tools-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cargo/bin/just
          ~/.cargo/bin/cargo-shear
        key: cache-tools

    - name: Install cargo-binstall
      if: steps.cache-tools-restore.outputs.cache-hit != 'true'
      uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c # v1.22.0

    - name: Install cargo-shear
      if: steps.cache-tools-restore.outputs.cache-hit != 'true'
      run: cargo binstall just cargo-shear -y
      shell: bash

    - name: Save CI tools
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: steps.cache-tools-restore.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.cargo/bin/just
          ~/.cargo/bin/cargo-shear
        key: cache-tools

    - name: Cache toolchain
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
