[package]
name = "kb"
version = "0.2.4"
authors = ["killbasa"]
edition = "2021"
repository = "https://github.com/killbasa/cli"
license = "MIT"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.76"
byte-unit = "5.1.2"
clap = { version = "4.4.11", features = ["derive"] }
clap_complete = "4.4.4"
confy = "0.5.1"
curl = "0.4.44"
dunce = "1.0.4"
git2 = "0.18.1"
glob = "0.3.1"
once_cell = "1.19.0"
open = "5.0.1"
openssl = "0.10.62"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
serde = { version = "1.0.193", features = ["derive"] }
spinoff = { version = "0.8.0", features = ["dots"] }
url = "2.5.0"
