[package]
name = "kb"
version = "0.1.0"
authors = ["killbasa"]
edition = "2021"
repository = "https://github.com/killbasa/cli"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
clap_complete = "4.4.1"
confy = "0.5.1"
curl = "0.4.44"
dunce = "1.0.4"
git2 = "0.18.0"
once_cell = "1.18.0"
open = "5.0.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
serde = { version = "1.0.188", features = ["derive"] }
spinoff = { version = "0.8.0", features = ["dots"] }
url = "2.4.1"
