[package]
name = "kb"
version = "0.1.0"
authors = ["killbasa"]
edition = "2021"
repository = "https://github.com/killbasa/cli"
license = "MIT"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.2", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
clap_complete = "4.3.1"
confy = "0.5.1"
log = { version = "0.4.18", features = ["std"] }
once_cell = "1.18.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
serde = { version = "1.0.164", features = ["derive"] }
